%% day6puzzle2 - Daniel Breslan - Advent Of Code 2019
day6puzzle2result = numel(shortestpath(graph(table(...
    readlines("input.txt").split(")"),'VariableNames',{'EndNodes'})),...
    "YOU","SAN")) - 3 %#ok<NOPTS> 